GearGrind/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('cars/', include('cars.urls')),
    path('social/', include('social.urls')),
    path('bidding/', include('bidding.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bidding/urls.py
from django.urls import path

from bidding.views import CreateBidView, ListBidView, DeleteBidView, UpdateBidView, TransactionListView

urlpatterns = [
    path('create/<int:car_id>/', CreateBidView.as_view(), name='place-bid'),
    path("list/", ListBidView.as_view(), name='list-bid'),
    path('delete/<int:pk>/', DeleteBidView.as_view(), name='delete-bid'),
    path('update/<int:pk>/', UpdateBidView.as_view(), name='update-bid'),
    path('transactions/<int:profile_id>/', TransactionListView.as_view(), name='transaction_history')

]

cars/urls.py
from django.urls import path
from django.views.generic import DetailView, UpdateView

from cars.views import CreateCarView, CarDetailView, CarUpdateView, CarDeleteView, start_auction, end_auction, \
    cancel_auction

urlpatterns = [
    path('create/', CreateCarView.as_view(), name='car-create'),
    path('detail/<int:pk>/', CarDetailView.as_view(), name='car-detail'),
    path('edit/<int:pk>/', CarUpdateView.as_view(), name='car-edit'),
    path('delete/<int:pk>/', CarDeleteView.as_view(), name='car-delete'),
    path('car/<int:car_id>/start-auction/', start_auction, name='start-auction'),
    path('car/<int:car_id>/end-auction/', end_auction, name='end-auction'),
    path('car/<int:car_id>/cancel-auction/', cancel_auction, name='cancel-auction'),

]

bidding/models.py
from django.db import models

from accounts.models import UserProfile
from bidding.managers import TransactionManager
from cars.models import Car


# Create your models here.

class Bid(models.Model):
    car = models.ForeignKey(
        Car,
        on_delete=models.CASCADE,
        related_name='bids'
    )
    bidder = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    timestamp = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return f'{self.bidder.username} bid {self.amount} BGN on {self.car}'

class Transaction(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    seller = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        related_name='sales'
    )

    buyer = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        related_name='purchases'
    )

    final_price = models.DecimalField(max_digits=10, decimal_places=2)
    completed_at = models.DateTimeField(auto_now_add=True)

    objects = TransactionManager()

    def __str__(self):
        return f'{self.car} for {self.final_price} BGN between {self.seller} and {self.buyer}'

bidding/forms.py
from django import forms

from bidding.models import Bid


class BidBaseForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['amount']

class CreateBidForm(BidBaseForm):
    pass

class UpdateBidForm(BidBaseForm):
    pass

bidding/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, UpdateView

from accounts.models import UserProfile
from bidding.forms import CreateBidForm, UpdateBidForm
from bidding.models import Bid, Transaction
from cars.models import Car


# Create your views here.

class CreateBidView(LoginRequiredMixin, CreateView):
    model = Bid
    form_class = CreateBidForm
    template_name = 'bidding/place_bid.html'

    def dispatch(self, request, *args, **kwargs):
        self.car = get_object_or_404(Car, id=self.kwargs['car_id'])

        if self.car.owner == request.user:
            return HttpResponseForbidden('cannot place a bid on your car')
        if not self.car.is_listed:
            return HttpResponseForbidden("This car is not listed for auction.")

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        existing_bid = Bid.objects.filter(car=self.car, bidder=self.request.user).first()

        bid = form.save(commit=False)

        if existing_bid:
            bid.pk = existing_bid.pk

        bid.car = self.car
        bid.bidder = self.request.user
        bid.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('car-detail', args=[self.car.id])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['car'] = self.car

        context['existing_bid'] = Bid.objects.filter(car=self.car, bidder=self.request.user).first()

        return context

class ListBidView(ListView):
    model = Bid
    template_name = 'bidding/list_bids.html'

    def get_queryset(self):
        return Bid.objects.filter(bidder=self.request.user)

class DeleteBidView(LoginRequiredMixin, DeleteView):
    model = Bid
    template_name = 'bidding/confirm_delete.html'
    success_url = reverse_lazy('list-bid')

    def get_queryset(self):
        return Bid.objects.filter(bidder=self.request.user)

class UpdateBidView(LoginRequiredMixin, UpdateView):
    model = Bid
    form_class = UpdateBidForm
    template_name = 'bidding/update_bid_form.html'
    success_url = reverse_lazy('list-bid')

class TransactionListView(ListView):
    model = Transaction
    template_name = 'bidding/transaction_history.html'
    def get_queryset(self):
        profile_id = self.kwargs.get('profile_id')
        profile = get_object_or_404(UserProfile, id=profile_id)
        return Transaction.objects.filter(Q(seller=profile) | Q(buyer=profile))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_id = self.kwargs.get('profile_id')
        profile = get_object_or_404(UserProfile, id=profile_id)
        context['profile'] = profile
        return context

templates/bidding/confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block page_class %}Confirm Delete{% endblock %}

{% block content %}
    <div style="padding: 20px; display: flex; flex-direction: column">
        <h2>Are you sure you want to delete your bid of {{ object.amount }} BGN
            on {{ object.car.make }} {{ object.car.model }}?</h2>

        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="buttons">Delete</button>
            <a href="{% url 'list-bid' %}" class="buttons">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/bidding/list_bids.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/list_bids.css' %}">
{% endblock %}

{% block page_class %}Your bids{% endblock %}

{% block content %}
    {% for bid in bid_list %}
        <div class="bidding">
            <h1>
                {{ bid.car.make }} {{ bid.car.model }}
            </h1>
            <h3>
                {{ bid.amount }} BGN
            </h3>
            <div class="bid-interaction">
                <a class="buttons" href="{% url 'delete-bid' bid.id %}">
                    Delete
                </a>
                <a class="buttons" href="{% url 'car-detail' bid.car.id %}">
                    Car detail
                </a>
                <a class="buttons" href="{% url 'update-bid' bid.id %}">
                    Change Amount
                </a>
            </div>
        </div>
    {% empty %}
        <h1 style="text-align: center">You have not bid on any car yet</h1>
    {% endfor %}
{% endblock %}

templates/bidding/place_bid.html
{% extends 'core/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/create-car.css' %}">
{% endblock %}
{% block title %}place bid{% endblock %}

{% block content %}
    {% if existing_bid %}
        <h1>You already have placed {{ existing_bid.amount }} BGN on {{ bid.car.owner.username }}'s {{ car.make }} {{ car.model }}</h1>
        <h3>Update your bid</h3>
    {% else %}
        <h1>Place your bid on {{ bid.car.owner.username }}'s {{ car.make }} {{ car.model }}</h1>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="buttons">Place Bid</button>
    </form>
{% endblock %}

templates/bidding/transaction_history.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/transaction_history.css' %}">
{% endblock %}

{% block page_class %}Transactions{% endblock %}

{% block content %}
    {% for transaction in transaction_list %}
        {% if profile == transaction.seller %}
            <div class="sale">
                <a href="{% url 'car-detail' transaction.car.id %}">
                    <img src="{{ transaction.car.image }}" alt="car details">
                </a>
                <h1>
                    <a href="{% url 'user-details' transaction.seller.id %}">
                        {{ transaction.seller }}
                    </a>
                    has sold his {{ transaction.car.make }} {{ transaction.car.model }}
                    to <a href="{% url 'user-details' transaction.buyer.id %}">{{ transaction.buyer }}</a>
                    for {{ transaction.final_price }} BGN
                </h1>
            </div>
        {% elif profile == transaction.buyer %}
            <div class="purchase">
                <a href="{% url 'car-detail' transaction.car.id %}">
                    <img src="{{ transaction.car.image }}" alt="car details">
                </a>
                <h1>
                    <a href="{% url 'user-details' transaction.seller.id %}">
                        {{ transaction.seller }}
                    </a>
                    has sold his {{ transaction.car.make }} {{ transaction.car.model }}
                    to <a href="{% url 'user-details' transaction.buyer.id %}">{{ transaction.buyer }}</a>
                    for {{ transaction.final_price }} BGN
                </h1>
            </div>
        {% endif %}
    {% empty %}
        {% if profile == user.request %}
            <h1>You have not made any transactions</h1>
        {% else %}
            <h1>{{ profile.username }} has not made any transactions</h1>
        {% endif %}
    {% endfor %}

{% endblock %}

templates/bidding/update_bid_form.html
{% extends 'core/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/create-car.css' %}">
{% endblock %}
{% block title %}place bid{% endblock %}

{% block content %}
    <h1>change the bid on {{ car.make }} {{ car.model }}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="buttons">Place Bid</button>
    </form>
{% endblock %}